export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INITIAL_INGREDIENTS = 'SET_INITIAL_INGREDIENTS';
export const SET_ERROR = 'SET_ERROR';
